### PR TITLE
Add issue templates for unit 1 pathways 2 and 3

### PR DESCRIPTION
**Pull request by sethlopez-bnr**
Issue templates are based on the [`basic-android-kotlin-compose-birthday-card-app` issue templates](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/tree/main/.github/ISSUE_TEMPLATE).

### CODE REVIEW

**Review by kkuan2011 — COMMENTED** [review]
Is it possible to remove the numbering (1-1-1) since those are more for internal use to track codelabs? Otherwise looks great!

**Comment by sethlopez-bnr** [comment]
@kkuan2011 Done! 👍

**Review by kkuan2011 — COMMENTED** [review]
Thanks @sethlopez-bnr, looks great! Once you remove the app-overview one, I can approve.

**Comment by sethlopez-bnr** [comment]
@kkuan2011 Done! 👍

**Review by kkuan2011 — APPROVED** [review]

**Pull request merged**
